/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'gregoryjeckell' at '5/29/15 1:22 PM' with Gradle 2.4
 *
 * @author gregoryjeckell, @date 5/29/15 1:22 PM
 */
public class Strategy {

    public abstract class Monster {

        // Monsters have behaviors, but they are specific to the type
        AttackBehavior attackBehavior;
        DefenseBehavior defenseBehavior;
        String name;

        public Monster() {}

        public abstract void display();

        public String performAttack() {
            return attackBehavior.attack();
        }

        public String performDefense() {
            return defenseBehavior.defend();
        }
    }

    public interface AttackBehavior {
        public String attack();
    }

    public interface DefenseBehavior {
        public String defend();
    }

    public class AttackWithAxe implements AttackBehavior {
        public String attack() {
            return "Axe attack!";
        }
    }

    public class DefendWithShield implements DefenseBehavior {
        public String defend() {
            return "Shield defend!";
        }
    }

    public class BearMonster extends Monster {

        public BearMonster(AttackBehavior a, DefenseBehavior d) {
            attackBehavior = a;
            defenseBehavior = d;
            name = "Bear!";
        }

        public void display() {
            System.out.println("Bear Monster!");
        }
    }
}

