import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'gregoryjeckell' at '5/29/15 1:22 PM' with Gradle 2.4
 *
 * @author gregoryjeckell, @date 5/29/15 1:22 PM
 */
public class StrategyTest {

    @Test public void testBearMonster() {
        AttackBehavior attack = new AttackWithAxe();
        DefenseBehavior defense = new DefendWithShield();
        Monster bear = new BearMonster(attack, defense);

        assertEquals("Bear!", bear.name);
    }

    @Test public void testBearAxeAttack() {
        AttackBehavior attack = new AttackWithAxe();
        DefenseBehavior defense = new DefendWithShield();
        Monster bear = new BearMonster(attack, defense);

        assertEquals("Axe attack!", bear.performAttack());
    }

    @Test public void testBearShieldDefense() {
        AttackBehavior attack = new AttackWithAxe();
        DefenseBehavior defense = new DefendWithShield();
        Monster bear = new BearMonster(attack, defense);

        assertEquals("Shield defend!", bear.performDefense());
    }

}
